".pdf" = ""
"Boostnote" = "ﴬ"
"alacritty" = ""
"calculator" = ""
"chrome" = ""
"disk usage" = ""
"docker" = ""
"file manager" = ""
"firefox" = ""
"github" = ""
"google" = ""
"gthumb" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"menu" = ""
"mpv" = ""
"music" = ""
"nvim" = ""
"private browsing" = ""
"rust" = ""
"slack" = ""
"tmux" = ""
"transmission" = ""
"vi" = ""
"videostream" = ""
"vim" = ""
"zsh" = ""
